########################################################################################################################
#
# GNSS solution message
#
# This message contains GNSS time expressed in the form of GNSS week number and time of week(in seconds),
# and is suitable for GVINS (HKUST-Aerial-Robotics)
#
########################################################################################################################

uint32 week
float64 tow