########################################################################################################################
#
# GNSS observation data definition for all satellites
#
# This message contains one-epoch measurements from multiple satellites and is suitable for GVINS (HKUST-Aerial-Robotics)
#
########################################################################################################################

GVINS_GNSSObsMsg[] meas